# The adb build-support lib: type constructors and mkExperiment.
# Types are authored here as nix values and rendered to plain JSON descriptors at eval
# time (ADB_MANIFEST); the runner and GUI consume JSON and never evaluate nix.
#
# `rev`/`narHash` describe the source tree being evaluated (null = unknown): the
# flake door passes them from its own sourceInfo, the classic door from the
# .git-revision stamp or the adbRev argument. `origin` is the fetchable ref without
# a rev — a source cannot know its own URL, so it is stated once at the call site.
# `adb-runner` arrives by argument, so overriding the runner reaches every
# experiment.
{ pkgs, origin, adb-runner, pyproject-nix, uv2nix, pyproject-build-systems
, rev ? null, narHash ? null
}:

let
  inherit (pkgs) lib;

  # The fetchable reproducibility ref: the pinned rev spliced into the origin ref (in
  # front of any ?dir=... query). This is NOT condition identity (see mkExperiment's
  # per-experiment content `source` below) — it is recorded per run so a run can be
  # re-run from a pinned source.
  refParts = lib.splitString "?" origin;
  fetchRef =
    if rev != null then
      builtins.head refParts + "/${rev}"
      + lib.optionalString (builtins.length refParts > 1)
        "?${lib.concatStringsSep "?" (builtins.tail refParts)}"
    else "dirty:${if narHash != null then narHash else "unknown"}";

  # types.llm governs its own hints: every llm-typed param gets the shared model
  # catalog (lib/model-catalog) appended to its suggestions at eval time, so no
  # experiment can desync from it. An experiment's own `suggestions` attr means
  # experiment-specific EXTRAS, prepended (e.g. hello's keyless mock) — never a
  # replacement. Presentation only: hints are not identity.
  llmSuggestions = import ../../lib/model-catalog/suggestions.nix { inherit lib; };
  # Applies to top-level params AND llm-typed fields inside listOf(struct) params
  # (e.g. a roster's per-agent model cell) — a struct field is a bare type or a
  # param-wrapped one; only fields that actually get hints are rewrapped.
  addHints = p: p // { suggestions = (p.suggestions or [ ]) ++ llmSuggestions; };
  withFieldHints = f:
    let p = if f ? kind then { type = f; } else f;
    in if (p.type.kind or null) == "llm" then addHints p else f;
  withLlmHints = params: lib.mapAttrs
    (_: p:
      if (p.type.kind or null) == "llm" then addHints p
      else if (p.type.kind or null) == "list" && (p.type.of.kind or null) == "struct"
      then p // {
        type = p.type // {
          of = p.type.of // { fields = lib.mapAttrs (_: withFieldHints) p.type.of.fields; };
        };
      }
      else p)
    params;

  # Dev-loop artifacts (a `uv run` .venv, __pycache__, build dists, direnv state)
  # are neither identity nor build input: they must not mint new conditions
  # (mkExperiment's `source` hash) and must not be imported into the store at
  # eval time — re-hashing a multi-hundred-MB .venv on every fresh eval was the
  # dominant cost of a classic-door eval.
  isDevArtifact = base:
    builtins.elem base [ ".venv" "__pycache__" "node_modules" "dist" ".direnv" ".pytest_cache" ".mypy_cache" ".ruff_cache" ]
    || base == "result" || lib.hasPrefix "result-" base;
  # import a source path with dev artifacts filtered out; content-addressed, so
  # an unchanged subtree re-imports for free
  cleanImport = name: path: builtins.path {
    inherit name path;
    filter = p: _type: !isDevArtifact (baseNameOf p);
  };
in
{
  # exported for the other source-import sites (web dist, the runner workspace) —
  # every path that enters the store goes through the same dev-artifact filter
  inherit cleanImport;

  # the generated GenerateConfig sub-form (lib/adb-inspect/generate_fields.json,
  # regenerated by `task genconfig:update`), exposed here so experiment
  # declarations never reach above their own directory with relative paths.
  # The schema comes from whichever adb package set is being evaluated.
  inspectGenerateFields =
    (builtins.fromJSON (builtins.readFile ../../lib/adb-inspect/generate_fields.json)).fields;

  types = rec {
    llm = { kind = "llm"; };
    str = { kind = "str"; };
    int = { kind = "int"; };
    float = { kind = "float"; };
    bool = { kind = "bool"; };
    enum = values: { kind = "enum"; inherit values; };
    listOf = of: { kind = "list"; inherit of; };
    # Only legal as listOf (struct { ... }) — the "table shape". Fields are scalar/registry
    # types only; the runner validates this when loading the manifest.
    struct = fields: { kind = "struct"; inherit fields; };
    # free-form JSON object — arbitrary keys/values, for a wrapped tool's passthrough
    # args (inspect's -T/generate config). The GUI renders it as a JSON editor; the
    # whole object is materialized into the condition hash as written.
    object = { kind = "object"; };

    # param wraps a type with defaults/instantiation-checks/presentation hints.
    param = type: attrs: { inherit type; } // attrs;
  };

  # mkPythonEnv: shared uv2nix setup using the toolchain supplied by the entrypoint.
  # Python sources come from uv.lock; local sources are filtered without
  # changing which directory or revision the lock selects.
  mkPythonEnv =
    { name
    , workspaceRoot
    , python ? pkgs.python313
    , sourcePreference ? "wheel"
      # extra pythonSet overlay for per-experiment-directory fixes (e.g. a git dep that ships a
      # legacy setup.py and needs setuptools injected as a build system). Receives
      # (final: prev: …) with uv2nix's pythonSet, where `final.resolveBuildSystem`
      # is available.
    , overrides ? (_final: _prev: { })
    }:
    let
      projectName = (builtins.fromTOML (builtins.readFile (workspaceRoot + "/pyproject.toml"))).project.name;
      workspace = uv2nix.lib.workspace.loadWorkspace { inherit workspaceRoot; };
      # Let uv2nix resolve sources, then filter local path sources using the
      # documented per-package overrideAttrs interface. Fetchers remain intact.
      projectOverlay = workspace.mkPyprojectOverlay { inherit sourcePreference; };
      filteredProjectOverlay = final: prev:
        lib.mapAttrs
          (_: package: package.overrideAttrs (old:
            lib.optionalAttrs (builtins.isPath (old.src or null)) {
              src = cleanImport "${old.pname}-src" old.src;
            }))
          (projectOverlay final prev);
      pythonSet =
        (pkgs.callPackage pyproject-nix.build.packages { inherit python; }).overrideScope
          (lib.composeManyExtensions [
            pyproject-build-systems.overlays.default
            filteredProjectOverlay
            overrides
          ]);
    in
    # Select the application only; editable local test dependencies are also
    # workspace members, but must not become runtime installation roots.
    pythonSet.mkVirtualEnv name { ${projectName} = [ ]; };

  # mkExperiment: the schema + program → a runnable flake app with the manifest JSON and
  # source identity baked in. `program` is whatever speaks the runner protocol (params
  # JSON on stdin → events through ADB_EVENT_SOCKET): a derivation (resolved via lib.getExe — the
  # usual case, a writeShellApplication adapter next to package.nix) or an explicit
  # executable path string.
  mkExperiment =
    { name
    , summary
    , params
    , results ? { }
    , env ? { }
      # external references for the experiment page — [{ label, url }]: the upstream
      # repo/docs, paper, datasets. Presentation only, never identity (not in `src`):
      # generated from a wrapped package's own declared metadata where it exists
      # (inspect_evals' listing), hand-written in the wrapper otherwise.
    , links ? [ ]
      # Plain Markdown catalog text, supplied from the package directory by the
      # registry. This field does not alter the experiment's declared `src`.
    , readme ? null
    , readmeAssets ? null
    , program
    , src           # the experiment's OWN identity sources: a path (usually `./.`) or a
                    # list of paths. See identity note below. Identity is strictly
                    # content — it records, never judges comparability; declared
                    # upstream versions are covariates/advisory input, not identity
                    # (docs/book/src/running/model.md).
    }:
    let
      programPath =
        if lib.isDerivation program then lib.getExe program else program;

      # Per-experiment content identity. The condition hash's `source` is a content
      # hash of THIS experiment's declared sources — each re-imported via builtins.path
      # so its hash depends ONLY on that subtree's content, never on the whole-repo
      # rev. So editing one experiment's directory cannot change another's condition_id.
      # The shared runner, wrapper lib, interpreter, and platform are NOT in identity;
      # they are recorded as run covariates. The fetchable rev (`fetchRef`) is recorded
      # separately for reproducibility — also not identity.
      srcs = if builtins.isList src then src else [ src ];
      # dev-loop artifacts are NOT identity (isDevArtifact above): a `uv run`
      # dropping a .venv into the subtree must not mint new conditions
      source = "content:sha256:" + builtins.hashString "sha256" (lib.concatStringsSep "\n"
        (lib.imap0 (i: p: "${cleanImport "adb-src-${name}-${toString i}" p}") srcs));

      # `origin` identifies the packaging repository in catalog metadata; it is
      # not part of `src` and is distinct from the pinned fetchRef
      manifest = pkgs.writeText "adb-manifest-${name}.json" (builtins.toJSON ({
        schema_version = 0;
        params = withLlmHints params;
        # Authors may use a bare type as shorthand; consumers always receive a
        # declaration, with optional presentation metadata preserved verbatim.
        results = lib.mapAttrs (_: result:
          if result ? kind then { type = result; } else result) results;
        inherit name summary env origin links;
      } // lib.optionalAttrs (readme != null) { inherit readme; }));
      app = pkgs.writeShellApplication {
        name = "adb-${name}";
        runtimeInputs = [ adb-runner ];
        text = ''
          export ADB_MANIFEST=${manifest}
          export ADB_EXPERIMENT_BIN=${lib.escapeShellArg programPath}
          export ADB_RUNNER_BIN=${lib.escapeShellArg (lib.getExe adb-runner)}
          export ADB_NIX_SYSTEM=${lib.escapeShellArg pkgs.stdenv.hostPlatform.system}
          export ADB_SOURCE=${lib.escapeShellArg source}
          export ADB_FETCH_REF=${lib.escapeShellArg fetchRef}
          exec "$ADB_RUNNER_BIN" "$@"
        '';
      };
    in
    { inherit app manifest name readmeAssets; };
}
